name: release
on:
  push:
    tags: [ 'v*' ]
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Configure Sonatype credentials
        run: |
          mkdir -p ~/.sbt/1.0
          cat > ~/.sbt/1.0/sonatype_credentials <<EOF
          realm=Sonatype Nexus Repository Manager
          host=central.sonatype.com
          user=$SONATYPE_USERNAME
          password=$SONATYPE_PASSWORD
          EOF
      - name: Import GPG key
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 -d | gpg --batch --import
      - name: Publish release bundle
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sbt 'set every publishTo := { val d = baseDirectory.value / "central-bundle"; Some("bundle" at s"file://${d.getAbsolutePath}") }' +publishSigned
          PROJECT=$(basename "$GITHUB_REPOSITORY")
          VERSION=${{ github.ref_name }}
          DATE=$(date +%Y%m%d)
          zip -rq "${PROJECT}-${VERSION}-${DATE}.zip" central-bundle
          curl -sf -u "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" -F bundle=@"${PROJECT}-${VERSION}-${DATE}.zip" "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
      - name: Publish SNAPSHOT
        if: github.ref == 'refs/heads/main'
        run: sbt +publishSigned
